-- Question 1
select * from SALES_DATASET_RFM_PRJ
alter table SALES_DATASET_RFM_PRJ
alter column priceeach type numeric using(trim(priceeach)::numeric);

-- Question 2
SELECT *
FROM SALES_DATASET_RFM_PRJ
WHERE 
  ORDERNUMBER IS NULL OR ORDERNUMBER = '';
SELECT *
FROM SALES_DATASET_RFM_PRJ
WHERE 
  QUANTITYORDERED IS NULL OR QUANTITYORDERED = '';
SELECT *
FROM SALES_DATASET_RFM_PRJ
WHERE 
  PRICEEACH IS NULL OR PRICEEACH = '';
SELECT *
FROM SALES_DATASET_RFM_PRJ
WHERE 
  ORDERLINENUMBER IS NULL OR ORDERLINENUMBER = '';
SELECT *
FROM SALES_DATASET_RFM_PRJ
WHERE 
  SALES IS NULL OR SALES = '';
SELECT *
FROM SALES_DATASET_RFM_PRJ
WHERE 
  ORDERDATE IS NULL OR ORDERDATE = '';
  
--QUESTION 03
ALTER TABLE SALES_DATASET_RFM_PRJ
ADD CONTACTLASTNAME VARCHAR(255),
ADD CONTACTFIRSTNAME VARCHAR(255);

UPDATE SALES_DATASET_RFM_PRJ
SET
  CONTACTLASTNAME = CONCAT(UPPER(LEFT(CONTACTFULLNAME, 1)),
						   LOWER(SUBSTRING(CONTACTFULLNAME, position('-' in CONTACTFULLNAME) - 1)));
 select * from SALES_DATASET_RFM_PRJ
   
-- QUESTION 04
ALTER TABLE SALES_DATASET_RFM_PRJ
ADD QTR_ID INT,
ADD MONTH_ID INT,
ADD YEAR_ID INT;
SELECT
  EXTRACT(QUARTER FROM ORDERDATE) AS QTR_ID,
  EXTRACT(MONTH FROM ORDERDATE) AS MONTH_ID,
  EXTRACT(YEAR FROM ORDERDATE) AS YEAR_ID
FROM SALES_DATASET_RFM_PRJ;

-- QUESTION 05
SELECT AVG(QUANTITYORDERED) AS Mean, STDDEV(QUANTITYORDERED) AS StdDev
FROM SALES_DATASET_RFM_PRJ;

SELECT *, (QUANTITYORDERED - Mean) / StdDev AS ZScore
FROM SALES_DATASET_RFM_PRJ;

-- QUESTION 06 
CREATE TABLE SALES_DATASET_RFM_PRJ_CLEAN AS
SELECT *
FROM SALES_DATASET_RFM_PRJ;
